[package]
name = "tryrust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bson]
version = "2.2.0"
features = ["chrono-0_4"]

[dependencies.serde_json]
version = "1.0"

[dependencies.chrono]
version = "0.4.19"
